version: "2"
run:
  timeout: 5m
  tests: true
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gocritic
    - gosec
    - ineffassign
    - unused
    - goconst
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - revive
        text: should have comment or be unexported
        source: ^func New.*$
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/lc/void
  exclusions:
    generated: lax
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$
